name: CI

#dispara o workflow a cada push e a cal pull request
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Run pytest
    runs-on: ubuntu-latest

    steps:
      # 1 - Baixar o código do repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # 2 - Instala o Python e as dependências necessárias para rodar os testes
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3 - Instalar o pytest
      - name: Instalarr dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # 4 - Executar os testes usando pytest
      - name: Executar tests
        run: pytest -v